name: habit_tracker
description: "Ultimate Habit & Fitness Tracker - A comprehensive local app for tracking workouts, habits, and tasks"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  flutter_slidable: ^3.1.1
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11

  # Charts and Analytics
  fl_chart: ^0.69.0

  # Date and Time
  table_calendar: ^3.1.2
  intl: ^0.20.2

  # Notifications and Alarms
  flutter_local_notifications: ^19.4.2
  android_alarm_manager_plus: ^4.0.3
  permission_handler: ^12.0.1

  # File Operations
  file_picker: ^8.1.2
  path_provider: ^2.1.4

  # Audio Player
  audioplayers: ^6.1.0

  # Icons and UI Enhancements
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Drag and Drop
  reorderable_grid_view: ^2.2.8
  awesome_notifications: ^0.10.1
  uuid: ^4.5.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
